Include led test from base
canonical/checkbox-provider-ce-oem pull request #35
Opened 2023-07-31 03:25 UTC by rickwu666666

Since we have migrated LED cases back to the checkbox base, we need to remove the existing job and nest the plan from the checkbox base.

2023-08-07 09:44 UTC, stanley31huang commented on README.md
> +SYS_LEDS={position1}:{path1} {position1}:{path2} ...
should be `SYS_LEDS={position1}:{path1} {position2}:{path2} ...`?

2023-08-07 09:46 UTC, stanley31huang requested changes
there's a minor issue in this PR, please see my inline comment

2023-08-08 01:23 UTC, rickwu666666 commented
> there's a minor issue in this PR, please see my inline comment

@stanley31huang I've fixed it. Thanks for the review.

2023-08-08 05:05 UTC, stanley31huang approved these changes
LGTM

2023-08-15 03:06 UTC, patliuu approved these changes
LGTM

2023-08-15 03:10 UTC, merged