Fix: nested plan for server manual
canonical/checkbox-provider-ce-oem pull request #44
Opened 2023-09-11 07:29 UTC by rickwu666666

Fix: nested plan for server manual

2023-09-11 08:48 UTC, stanley31huang requested changes
there're two incorrect nested plan in the manual test plan for server, please also fix it as well.

2023-09-11 14:28 UTC, zongminl requested changes

2023-09-12 02:47 UTC, rickwu666666 commented on checkbox-provider-ce-oem/units/test-plan-ce-oem-full-classic.pxu
>      after-suspend-ce-oem-automated
Updated. Thanks!

2023-09-12 02:47 UTC, rickwu666666 commented
> there're two incorrect nested plan in the manual test plan for server, please also fix it as well.

Updated. Thanks!

2023-09-14 05:08 UTC, LiaoU3 approved these changes
LGTM

2023-09-27 08:07 UTC, patliuu approved these changes
LGTM

2023-09-28 00:48 UTC, merged