Add: rpmsg tests for i.MX and TI processors
canonical/checkbox-provider-ce-oem pull request #46
Opened 2023-09-19 07:20 UTC by stanley31huang

adding rpmsg tests for i.MX and TI processors

#### Test submissions
https://certification.canonical.com/hardware/202212-30918/submission/332376/

#### Unit test results
stanley@stanley-ThinkPad-T490:~/Desktop/Git_Repos/iot/checkbox-provider-ce-oem/checkbox-provider-ce-oem/tests$ python3 -m unittest -v
test_arm_processor_am62 (test_rpmsg_tests.RpmsgTests)
Checking if the CPU processor manufacture is TI ... SoC family is AM62X, machine is Texas Instruments AM625 SK
ok
test_arm_processor_imx (test_rpmsg_tests.RpmsgTests)
Checking if the CPU processor manufacture is i.MX ... SoC family is Freescale i.MX, machine is Honeywell i.MX8MM X8Med35 PDK
ok
test_arm_processor_unexpected (test_rpmsg_tests.RpmsgTests)
/sys/devices/soc0/family and machine fils not exists ... SoC family is , machine is 
ok
test_rpmsg_device_exist (test_rpmsg_tests.RpmsgTests)
Checking RPMSG device is available ... ## Checking RPMSG device is available ...
RPMSG device is available
ok
test_rpmsg_device_not_exist (test_rpmsg_tests.RpmsgTests)
Checking RPMSG device is not available ... ## Checking RPMSG device is available ...
ok

----------------------------------------------------------------------
Ran 5 tests in 0.004s

OK

2023-09-22 03:29 UTC, LiaoU3 requested changes
@stanley31huang Please see my in-line comment.

2023-09-22 05:39 UTC, stanley31huang commented on checkbox-provider-ce-oem/bin/rpmsg_tests.py
> +            soc_machine = fp.read().strip()
the scripts will raise a SystemExit in pingpong function. And we would like to collect both family and machine while doing the testing
```
SystemExit("Unexpected CPU type.")
```

2023-09-22 05:40 UTC, stanley31huang commented on checkbox-provider-ce-oem/bin/rpmsg_tests.py
> +            soc_family = fp.read().strip()
the scripts will raise a SystemExit in pingpong function. And we would like to collect both family and machine while doing the testing
```
SystemExit("Unexpected CPU type.")
```

2023-09-22 05:44 UTC, stanley31huang commented on checkbox-provider-ce-oem/bin/rpmsg_tests.py
> +    path = "/sys/devices/soc0/family"
fixed

2023-09-22 05:45 UTC, stanley31huang commented on checkbox-provider-ce-oem/bin/rpmsg_tests.py
> +    path = "/sys/devices/soc0/machine"
fixed

2023-09-22 05:45 UTC, stanley31huang commented on checkbox-provider-ce-oem/bin/rpmsg_tests.py
> +        if machine.find("Texas Instruments") != -1:
fixed

2023-09-22 07:42 UTC, LiaoU3 commented on checkbox-provider-ce-oem/bin/rpmsg_tests.py
> +            soc_machine = fp.read().strip()
Copy that

2023-09-22 07:43 UTC, LiaoU3 commented on checkbox-provider-ce-oem/bin/rpmsg_tests.py
> +            soc_family = fp.read().strip()
Copy that

2023-09-22 07:44 UTC, LiaoU3 approved these changes
LGTM

2023-09-27 08:01 UTC, patliuu requested changes

2023-09-27 08:01 UTC, patliuu commented on checkbox-provider-ce-oem/units/rpmsg/jobs.pxu
> +estimated_duration: 60
Detect job should not need 60 seconds, right? :smile:

2023-10-06 06:17 UTC, patliuu approved these changes
LGTM

2023-10-06 06:44 UTC, merged